### ISSUE TITLE
Import error.

### ISSUE THREAD

**Issue by nehalagrawal-blu** [mikepenz/xray-action#219]
Hi, I keep getting import error when the xray step is run.
Code in yaml file : 
```
name: xray-action
if: always()
uses: mikepenz/xray-action@v1.1.1
with:
    username: ${{ secrets.XRAY_CLIENT_ID }}
    password: ${{ secrets.XRAY_CLIENT_SECRET }}
    testFormat: "junit"
    testPaths: "**/test-result-reports/*-junit.xml"
    projectKey: "QA"
```

Error - 
```
Run mikepenz/xray-action@v1.1.1
  with:
    username: ***
    password: ***
    testFormat: junit
    testPaths: **/test-result-reports/*-junit.xml
    projectKey: QA
    xrayCloud: true
    combineInSingleTestExec: false
    failOnImportError: false
    continueOnImportError: true
    importParallelism: 2
🚀 Connect to xray
  ℹ️ Configured XrayCloud
  ℹ️ Start logging in procedure to xray
  ℹ️ Completed login and retrieved token
📝 Import test reports
  ℹ️ Importing from: **/test-result-reports/*-junit.xml
  ℹ️ Importing using format: junit
  Warning: 🔥 Failed to import: /home/runner/work/portal/portal/test-result-reports/jest-junit.xml (Timeout awaiting 'request' for 60000ms)
  ℹ️ Processed 0 of 1 elements. Failed to import: 1
```

Can someone help me understand whats wrong?
