### ISSUE TITLE
Unable to access output values

### ISSUE THREAD

**Issue by kormachevt** [mikepenz/xray-action#466]
Hi ! I have some trouble to access output values. Maybe you can help me with it ?
Action creates Test Execution in Xray successfuly but I can't get testExecKey from the outputs of the step.

This is my part of workflow:

```
      - name: Import results to Xray
        id: import-xray
        uses: mikepenz/xray-action@v2.3.0
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "**/reports/jest-junit.xml"
          projectKey: "QA"
          testEnvironments: SBX
          combineInSingleTestExec: true

      - name: Print report link
        run: | 
          echo "https://some-company-name.atlassian.net/browse/${{steps.import-xray.outputs.testExecKey}}"        
```

And it just prints nothing instead of the output value:
![flow](https://user-images.githubusercontent.com/58318654/156538778-fde6f77a-f728-48a0-9f85-ae7d06bb2329.JPG)

I've tried it with all outputs of this action with the same result.
