### ISSUE TITLE
Enhance error messages instead of general 400 Bad Request response

### ISSUE THREAD

**Issue by andrewrybak** [mikepenz/xray-action#692]
Hello, I've faced the issue when I haven't created Environment variables in my Jira XRay, but added it to the GitHub Actions workflow and received 400 Bad Request, thus stuck for the whole day debugging what was wrong with the pipeline

Example of action:
```
- name: "Import results to Xray"
        uses: mikepenz/xray-action@v2.4.6
        with:
          username: ${{ steps.vault.outputs.XRAY_CLIENT_ID }}
          password: ${{ steps.vault.outputs.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "**/playwright-report/*.xml"
          projectKey: "ProjectId"
          testEnvironments: ${{ env.TEST_ENV }}  <- this field wasn't created in XRay
```

Error message in GitHub Actions:

```
ℹ️ Configured XrayCloud
ℹ️ Start logging in procedure to xray
ℹ️ Completed login and retrieved token
##[endgroup***
##[group***📝 Import test reports
ℹ️ Importing from: /playwright-report/*.xml
ℹ️ Importing using format: junit
##[warning***🔥 Failed to import: /playwright-report/results.xml (HTTPError: Response code 400 (Bad Request))
ℹ️ Processed 0 of 1 elements. Failed to import: 0
##[endgroup***
```

The real error that I checked using the Postman API call:

```
{
    "error": "Error importing results: the following environments don't exist or are not in the context of test execution project: 'dev'!"
}
```

Please, enhance error messages instead of general errors as it is going to be way easier to troubleshoot issues.

P.S. thanks for awesome action for XRay!
